/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Tenant struct {
	Id string `json:"id,omitempty"`
	Name string `json:"Name,omitempty"`
	ShortName string `json:"ShortName,omitempty"`
	SJTenantId int32 `json:"SJTenantId,omitempty"`
	SJAPIKey string `json:"SJAPIKey,omitempty"`
	SJPrintNodeAccountId string `json:"SJPrintNodeAccountId,omitempty"`
	Notes string `json:"Notes,omitempty"`
}
