/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwRolePermissionSet struct {
	RoleId int32 `json:"RoleId,omitempty"`
	PermissionSetId int32 `json:"PermissionSetId,omitempty"`
	IsDeny bool `json:"IsDeny,omitempty"`
}
