/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwApplication struct {
	ApplicationId int32 `json:"ApplicationId,omitempty"`
	ApplicationKey string `json:"ApplicationKey,omitempty"`
	Name string `json:"Name"`
	ApiUrl string `json:"ApiUrl,omitempty"`
	UiUrl string `json:"UiUrl,omitempty"`
	RequiresApplicationAccess bool `json:"RequiresApplicationAccess,omitempty"`
}
