/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwAssignedPermissionSet struct {
	PermissionSetId int32 `json:"PermissionSetId,omitempty"`
	ApplicationId int32 `json:"ApplicationId,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	IsEnabled bool `json:"IsEnabled,omitempty"`
	IsDeny bool `json:"IsDeny,omitempty"`
}
