/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RwRole struct {
	RoleId int32 `json:"RoleId,omitempty"`
	Name string `json:"Name"`
	StartDate time.Time `json:"StartDate,omitempty"`
	EndDate time.Time `json:"EndDate,omitempty"`
	IsEnabled bool `json:"IsEnabled,omitempty"`
	ApplicationId int32 `json:"ApplicationId"`
}
