/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RwRoleGroup struct {
	RoleId int32 `json:"RoleId,omitempty"`
	GroupId string `json:"GroupId,omitempty"`
	StartDate time.Time `json:"StartDate,omitempty"`
	EndDate time.Time `json:"EndDate,omitempty"`
	GroupName string `json:"GroupName,omitempty"`
}
