/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwUserType string

// List of RwUserType
const (
	EMPLOYEE_RwUserType RwUserType = "Employee"
	GROUP_RwUserType RwUserType = "Group"
	CUSTOMER_RwUserType RwUserType = "Customer"
	CARRIER_RwUserType RwUserType = "Carrier"
	FACILITY_RwUserType RwUserType = "Facility"
	ADMIN_RwUserType RwUserType = "Admin"
	FREIGHT_SERVICES_RwUserType RwUserType = "FreightServices"
)
