/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwPermissionReportItem struct {
	AppKey string `json:"AppKey,omitempty"`
	EntityType string `json:"EntityType,omitempty"`
	EntityId string `json:"EntityId,omitempty"`
	Title string `json:"Title,omitempty"`
	IsDeny bool `json:"IsDeny,omitempty"`
	IsUiPermission bool `json:"IsUiPermission,omitempty"`
	Key string `json:"Key,omitempty"`
	TypeName string `json:"TypeName,omitempty"`
	IsSerializable bool `json:"IsSerializable,omitempty"`
	Children []StringRwPermissionReportItemITreeNode `json:"Children,omitempty"`
	DepthFromRoot int32 `json:"DepthFromRoot,omitempty"`
	HasChildren bool `json:"HasChildren,omitempty"`
	Id string `json:"Id,omitempty"`
	HashProvider *IHashFunction `json:"HashProvider,omitempty"`
	PathId string `json:"PathId,omitempty"`
	IndentCharacter string `json:"IndentCharacter,omitempty"`
	IndentString string `json:"IndentString,omitempty"`
	Parent *StringRwPermissionReportItemITreeNode `json:"Parent,omitempty"`
	ParentId string `json:"ParentId,omitempty"`
	Root *StringRwPermissionReportItemITreeNode `json:"Root,omitempty"`
	RootId string `json:"RootId,omitempty"`
	Siblings []StringRwPermissionReportItemITreeNode `json:"Siblings,omitempty"`
	SortableTreePath string `json:"SortableTreePath,omitempty"`
	TreeNodeId string `json:"TreeNodeId,omitempty"`
}
