/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserTenant struct {
	ADUserId string `json:"ADUserId,omitempty"`
	TenantId string `json:"TenantId,omitempty"`
}
