/*
 * Redwood User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RwLoadRunnerAdUser struct {
	UserId int32 `json:"UserId,omitempty"`
	DisplayName string `json:"DisplayName,omitempty"`
	ContactId int32 `json:"ContactId,omitempty"`
	Email string `json:"Email,omitempty"`
	UserType *RwUserType `json:"UserType,omitempty"`
	IsEnabled bool `json:"IsEnabled,omitempty"`
	AdUserId string `json:"AdUserId,omitempty"`
	FirstName string `json:"FirstName,omitempty"`
	LastName string `json:"LastName,omitempty"`
	JobTitle string `json:"JobTitle,omitempty"`
}
